#!/bin/bash

# Prettify all JavaScript staged files
js_files=$(git diff --cached --name-only --diff-filter=ACM "*.js*" "*.md" | tr '\n' ' ')

if [ -n "$js_files" ] ; then
  echo "$js_files" | xargs npm run code:format
  echo "$js_files" | xargs git add
fi

exit 0
