d3.time.second
d3.time.minute
d3.time.hour
d3.time.day
d3.time.sunday
d3.time.monday
d3.time.tuesday
d3.time.wednesday
d3.time.thursday
d3.time.friday
d3.time.saturday
d3.time.week
d3.time.month
d3.time.year

d3.time.second.utc
d3.time.minute.utc
d3.time.hour.utc
d3.time.day.utc
d3.time.sunday.utc
d3.time.monday.utc
d3.time.tuesday.utc
d3.time.wednesday.utc
d3.time.thursday.utc
d3.time.friday.utc
d3.time.saturday.utc
d3.time.week.utc
d3.time.month.utc
d3.time.year.utc

d3.time.seconds
d3.time.minutes
d3.time.hours
d3.time.days
d3.time.sundays
d3.time.mondays
d3.time.tuesdays
d3.time.wednesdays
d3.time.thursdays
d3.time.fridays
d3.time.saturdays
d3.time.weeks
d3.time.months
d3.time.years

d3.time.seconds.utc
d3.time.minutes.utc
d3.time.hours.utc
d3.time.days.utc
d3.time.sundays.utc
d3.time.mondays.utc
d3.time.tuesdays.utc
d3.time.wednesdays.utc
d3.time.thursdays.utc
d3.time.fridays.utc
d3.time.saturdays.utc
d3.time.weeks.utc
d3.time.months.utc
d3.time.years.utc
