name: Unit testing, formatting & linting

on: [push]

jobs:
  testing-formatting-linting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - "8"
          - "10"
          - "11"
          - "12"
          - "13"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn
      - run: yarn test
      - run: yarn code:format:check
